subdomain: "heetmeisje"
user: "rutger.vvdk@gmail.com"
key: "umRMH1rGHBz6EYT1ww9x9F19"
lanes:
  - backlog
  - dev
  - progress
  - done
laneIds:
  backlog:
    name: Backlog
    transition: 11
    id: 10000
  dev:
    name: "Selected for Development"
    transition: 21
    id: 10001
  progress:
    name: "In Progress"
    transition: 31
    id: 4
  done:
    name: Done
    transition: 41
    id: 3