name: JiraChest
version: ${project.version}
main: me.rutger.jirachest.JiraChest
api-version: 1.16
authors: [ Rutger ]
description: Jiraboard build with chests!
softdepend: [HolographicDisplays]
commands:
  setchest:
  setsync:
  getholos:
  clearholos:
  listchests:
  clearchests:
  test: